/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-12-20 13:07:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import infra.PostDAO;
import infra.Post;

public final class postForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("infra.PostDAO");
    _jspx_imports_classes.add("infra.Post");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"externalLib/ckeditor/ckeditor.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./script/map.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("  src=\"https://code.jquery.com/jquery-3.6.0.js\"\r\n");
      out.write("  integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\"\r\n");
      out.write("  crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script src=\"./script/script.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"style/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');

		if(session.getAttribute("ifmbId") == null) {
			out.print("<script>alert('로그인 후 이용 가능합니다.'); history.back(); </script>");
			return;
		}	
			
	
      out.write("\r\n");
      out.write("	<div class=\"wrap postWrap\">\r\n");
      out.write("		<form action='execute.jsp?process=post' method='post' >\r\n");
      out.write("			<div class=\"postTextWrap\">\r\n");
      out.write("				<div class=\"formBox\">\r\n");
      out.write("					<label>작성자</label><input type=\"text\" name=\"ifptWirter\" readOnly value='");
      out.print(session.getAttribute("ifmbId"));
      out.write("'>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"formBox\">\r\n");
      out.write("					<label>제목</label><input type=\"text\" name=\"ifptTitle\" >\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"formBox\"> \r\n");
      out.write("					<label>지역 설정</label> \r\n");
      out.write("					<select id=\"ifptSido\" name=\"ifrgSido\">\r\n");
      out.write("						<option value=\"\">시/도</option>\r\n");
      out.write("					</select>\r\n");
      out.write("					<select id=\"ifptSigungu\" name=\"ifrgSigungu\">\r\n");
      out.write("						<option value=\"\">시/군/구</option>\r\n");
      out.write("					</select>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"formBox radioBox\">\r\n");
      out.write("					<label>공개여부</label>\r\n");
      out.write("					공개 <input type=\"radio\" name=\"ifptPublicNy\" value=\"1\" checked>\r\n");
      out.write("					비공개 <input type=\"radio\" name=\"ifptPublicNy\" value=\"0\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "map.jsp", out, false);
      out.write("<br><br><br>\r\n");
      out.write("			<textarea name=\"ifptContent\" id=\"ifptContent\" rows=\"10\" cols=\"100\" ></textarea>\r\n");
      out.write("			<div class=\"btnBox\">\r\n");
      out.write("				<button type=\"submit\">글작성</button>\r\n");
      out.write("				<button type=\"button\" onclick=\"history.go(-1)\">돌아가기</button>\r\n");
      out.write("				<div class=\"clear\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("		</form>\r\n");
      out.write("		<br><br><br>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("		createSidoOption();\r\n");
      out.write("	\r\n");
      out.write("		CKEDITOR.replace( \r\n");
      out.write("            'ifptContent'\r\n");
      out.write("            ,{ \r\n");
      out.write("                width : \"100%\"\r\n");
      out.write("                ,height : \"500px\"\r\n");
      out.write("                ,enterMode : 2\r\n");
      out.write("                , extraPlugins: 'image2,uploadimage'\r\n");
      out.write("                , filebrowserImageUploadUrl: 'execute.jsp?process=upload'\r\n");
      out.write("                , uploadUrl: \"execute.jsp?process=upload\"\r\n");
      out.write("               	//,extraPlugins: 'easyimage'\r\n");
      out.write("            }\r\n");
      out.write("   			\r\n");
      out.write("        );\r\n");
      out.write("		let process = \"");
      out.print(request.getParameter("process"));
      out.write("\";\r\n");
      out.write("		let post;\r\n");
      out.write("		if(process == \"update\") {\r\n");
      out.write("			let form = document.querySelector(\"form\");\r\n");
      out.write("			post = JSON.parse(getOne(");
      out.print(request.getParameter("ifptSeq"));
      out.write("));\r\n");
      out.write("			let publicNy = post['ifptPublicNy'];\r\n");
      out.write("			form.setAttribute(\"action\",\"execute.jsp?process=update&ifptSeq=\"+post['ifptSeq']);\r\n");
      out.write("			$(\"input[name='ifptTitle']\").val(post['ifptTitle']);\r\n");
      out.write("			CKEDITOR.instances.ifptContent.setData(post['ifptContent']);\r\n");
      out.write("			$(\"input[value=\"+publicNy+\"]\").prop(\"checked\", true);\r\n");
      out.write("			fill(post['ifrgSido'],post['ifrgSigungu'],1);\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
